export const PROPERTIES = [
  {
    id: 1,
    name: 'Skyline Residences',
    locality: 'Baner',
    price: '₹85 Lakh',
    priceRaw: 8500000,
    type: 'Apartment',
    bhk: '2 BHK',
    area: 950,
    floor: '8th of 14',
    status: 'Ready to Move',
    badge: 'HOT DEAL',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    description: 'Premium 2BHK apartment with modern amenities, stunning city views, and excellent connectivity to IT hubs.',
  },
  {
    id: 2,
    name: 'The Meridian',
    locality: 'Hinjewadi',
    price: '₹1.2 Crore',
    priceRaw: 12000000,
    type: 'Apartment',
    bhk: '3 BHK',
    area: 1400,
    floor: '12th of 18',
    status: 'Under Construction',
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    description: 'Luxury 3BHK residences in the heart of Hinjewadi IT Park zone with world-class clubhouse.',
  },
  {
    id: 3,
    name: 'NestVault Greens',
    locality: 'Wakad',
    price: '₹67 Lakh',
    priceRaw: 6700000,
    type: 'Apartment',
    bhk: '2 BHK',
    area: 850,
    floor: '5th of 12',
    status: 'Ready to Move',
    badge: 'HOT DEAL',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    description: 'Affordable luxury in Wakad with landscaped gardens, gym, and swimming pool.',
  },
  {
    id: 4,
    name: 'Prestige Towers',
    locality: 'Kharadi',
    price: '₹1.8 Crore',
    priceRaw: 18000000,
    type: 'Apartment',
    bhk: '3 BHK',
    area: 1800,
    floor: '20th of 28',
    status: 'Ready to Move',
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    description: 'Ultra-luxury high-rise in Kharadi IT corridor with panoramic views and premium finishes.',
  },
  {
    id: 5,
    name: 'Vista Commercial Hub',
    locality: 'Baner',
    price: '₹2.4 Crore',
    priceRaw: 24000000,
    type: 'Commercial',
    bhk: 'Commercial',
    area: 2200,
    floor: '3rd of 8',
    status: 'Ready to Move',
    badge: 'HOT DEAL',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    description: 'Grade A commercial space ideal for offices, clinics, and showrooms in prime Baner location.',
  },
  {
    id: 6,
    name: 'Serene Villas',
    locality: 'Undri',
    price: '₹3.2 Crore',
    priceRaw: 32000000,
    type: 'Villa',
    bhk: '4 BHK',
    area: 3200,
    floor: 'G+1 Villa',
    status: 'Under Construction',
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    description: 'Exclusive villa township with private garden, home theatre, and community clubhouse.',
  },
  {
    id: 7,
    name: 'Oasis Residency',
    locality: 'Viman Nagar',
    price: '₹95 Lakh',
    priceRaw: 9500000,
    type: 'Apartment',
    bhk: '2 BHK',
    area: 1050,
    floor: '7th of 15',
    status: 'Ready to Move',
    badge: 'HOT DEAL',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    description: 'Meticulously designed 2BHK near Pune airport with smart home features.',
  },
  {
    id: 8,
    name: 'Emerald Heights',
    locality: 'Wakad',
    price: '₹1.45 Crore',
    priceRaw: 14500000,
    type: 'Apartment',
    bhk: '3 BHK',
    area: 1550,
    floor: '15th of 22',
    status: 'Under Construction',
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&q=80',
    description: 'Sky-high 3BHK with wrap-around balcony, modular kitchen, and premium fittings.',
  },
  {
    id: 9,
    name: 'Greenfield Plots',
    locality: 'Undri',
    price: '₹48 Lakh',
    priceRaw: 4800000,
    type: 'Plots',
    bhk: 'Plot',
    area: 1200,
    floor: 'NA-approved',
    status: 'Ready to Move',
    badge: 'HOT DEAL',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    description: 'Residential plots in gated township with 24x7 security and all utilities.',
  },
  {
    id: 10,
    name: 'Corporate Square',
    locality: 'Hinjewadi',
    price: '₹3.6 Crore',
    priceRaw: 36000000,
    type: 'Commercial',
    bhk: 'Commercial',
    area: 3000,
    floor: '6th of 10',
    status: 'Ready to Move',
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
    description: 'Premium office spaces in Hinjewadi Phase 1 with dedicated parking and power backup.',
  },
  {
    id: 11,
    name: 'Maple Grove Villas',
    locality: 'Kharadi',
    price: '₹2.8 Crore',
    priceRaw: 28000000,
    type: 'Villa',
    bhk: '3 BHK',
    area: 2600,
    floor: 'G+1 Villa',
    status: 'Under Construction',
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800&q=80',
    description: 'Row house villas in integrated township near EON IT Park.',
  },
  {
    id: 12,
    name: 'Blue Horizon Apartments',
    locality: 'Viman Nagar',
    price: '₹1.1 Crore',
    priceRaw: 11000000,
    type: 'Apartment',
    bhk: '2 BHK',
    area: 1100,
    floor: '10th of 16',
    status: 'Ready to Move',
    badge: 'HOT DEAL',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    description: 'Luxury 2BHK with rooftop infinity pool and sky lounge near Kalyani Nagar.',
  },
];

export const LOCALITIES = [
  {
    name: 'Baner',
    avgPrice: '₹8,500 – ₹12,000/sqft',
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f28320c6?w=600&q=80',
    listings: 24,
  },
  {
    name: 'Hinjewadi',
    avgPrice: '₹6,500 – ₹9,500/sqft',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80',
    listings: 31,
  },
  {
    name: 'Wakad',
    avgPrice: '₹7,000 – ₹10,000/sqft',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80',
    listings: 18,
  },
  {
    name: 'Kharadi',
    avgPrice: '₹9,000 – ₹13,500/sqft',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=600&q=80',
    listings: 22,
  },
  {
    name: 'Undri',
    avgPrice: '₹5,500 – ₹8,000/sqft',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=600&q=80',
    listings: 15,
  },
  {
    name: 'Viman Nagar',
    avgPrice: '₹10,000 – ₹15,000/sqft',
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e6df5?w=600&q=80',
    listings: 19,
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Rahul & Priya Sharma',
    property: '3 BHK in Baner',
    avatar: 'https://i.pravatar.cc/80?img=11',
    rating: 5,
    review: "NestVault made our dream home a reality. From our first consultation to the keys in our hands, every step was handled with utmost professionalism. They found us the perfect home in Baner within our budget and the entire process was completely transparent. Cannot recommend them enough!",
  },
  {
    id: 2,
    name: 'Vikram Mehta',
    property: 'Commercial Space in Kharadi',
    avatar: 'https://i.pravatar.cc/80?img=33',
    rating: 5,
    review: "I've worked with multiple brokers in Pune but NestVault stands apart. Their knowledge of the Kharadi commercial market is unparalleled. They helped me close a grade-A office deal at a price I thought was impossible. Their legal team handled every document flawlessly.",
  },
  {
    id: 3,
    name: 'Sneha Kulkarni',
    property: '2 BHK in Wakad',
    avatar: 'https://i.pravatar.cc/80?img=47',
    rating: 5,
    review: "As a first-time buyer, I was completely lost. NestVault assigned me a dedicated advisor who patiently explained everything — RERA, home loans, registration. They held my hand through the entire journey. Moved into my new apartment last month and I couldn't be happier!",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: 'Pune Real Estate Market Report: Q2 2025',
    category: 'Investment',
    date: 'June 5, 2025',
    excerpt: 'Pune continues to be one of India\'s most resilient real estate markets. Q2 2025 saw a 14% surge in residential registrations with Hinjewadi and Kharadi leading the charge.',
    image: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=600&q=80',
    readTime: '6 min read',
  },
  {
    id: 2,
    title: 'Under-Construction vs Ready-to-Move: What Makes Sense in 2025?',
    category: 'Guide',
    date: 'May 22, 2025',
    excerpt: 'The age-old dilemma for property buyers. We break down the pros, cons, tax implications, and current market dynamics to help you make the right call.',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80',
    readTime: '8 min read',
  },
  {
    id: 3,
    title: 'Top 5 Localities for ₹60L Budget in Pune',
    category: 'Locality Guide',
    date: 'May 10, 2025',
    excerpt: 'Working with a ₹60 lakh budget doesn\'t mean compromising on quality. These 5 Pune localities offer excellent value, strong rental yields, and future appreciation.',
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&q=80',
    readTime: '5 min read',
  },
];

export const TEAM = [
  {
    name: 'Arjun Nair',
    role: 'Founder & Managing Director',
    experience: '14 Years',
    avatar: 'https://i.pravatar.cc/120?img=12',
    bio: 'Pune real estate veteran who founded NestVault with a vision to bring transparency and trust to property transactions.',
  },
  {
    name: 'Kavita Desai',
    role: 'Head of Residential Sales',
    experience: '10 Years',
    avatar: 'https://i.pravatar.cc/120?img=25',
    bio: 'Expert in luxury residential properties with a track record of closing 50+ premium transactions annually.',
  },
  {
    name: 'Rohan Joshi',
    role: 'Commercial Properties Lead',
    experience: '9 Years',
    avatar: 'https://i.pravatar.cc/120?img=15',
    bio: 'Specialized in Grade A commercial spaces, IT park proximity properties, and high-yield investment assets.',
  },
  {
    name: 'Meera Patil',
    role: 'Customer Experience Manager',
    experience: '7 Years',
    avatar: 'https://i.pravatar.cc/120?img=44',
    bio: 'Ensures every client journey is seamless from first enquiry through registration and handover.',
  },
];

export const PARTNERS = [
  'Godrej Properties',
  'Lodha Group',
  'Kolte-Patil',
  'Mahindra Lifespace',
  'Piramal Realty',
  'Sobha Developers',
];

export const STATS = [
  { value: '10+', label: 'Years Experience' },
  { value: '500+', label: 'Families Settled' },
  { value: '₹200Cr+', label: 'In Transactions' },
  { value: '4.9★', label: 'Google Rating' },
];

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Free Consultation',
    description: 'Share your requirements and budget. Our experts listen before they advise.',
    icon: '💬',
  },
  {
    step: 2,
    title: 'Shortlisting',
    description: 'We curate a handpicked list of properties matching your needs.',
    icon: '📋',
  },
  {
    step: 3,
    title: 'Site Visits',
    description: 'Scheduled guided visits to your shortlisted properties at your convenience.',
    icon: '🏠',
  },
  {
    step: 4,
    title: 'Negotiation',
    description: 'Our experts negotiate the best price and terms on your behalf.',
    icon: '🤝',
  },
  {
    step: 5,
    title: 'Legal & Registration',
    description: 'End-to-end documentation, RERA verification, and legal support.',
    icon: '📜',
  },
  {
    step: 6,
    title: 'Happy Handover',
    description: 'Receive the keys to your new home with our full-circle support.',
    icon: '🗝️',
  },
];
